# Generated by Django 3.2.22 on 2024-07-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
