# Generated by Django 3.2.22 on 2024-07-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(null=True, related_name='posts', to='blog.Category'),
        ),
    ]
