# Generated by Django 3.2.22 on 2024-07-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(default='', related_name='posts', to='blog.Category'),
        ),
    ]
